export const GET_UNIVERSITIES_REQUEST = "GET_UNIVERSITIES_REQUEST";
export const GET_UNIVERSITIES_SUCCESS = "GET_UNIVERSITIES_SUCCESS";
export const GET_UNIVERSITIES_FAILURE = "GET_UNIVERSITIES_FAILURE";

export const GET_FACULTIES_REQUEST = "GET_FACULTIES_REQUEST";
export const GET_FACULTIES_SUCCESS = "GET_FACULTIES_SUCCESS";
export const GET_FACULTIES_FAILURE = "GET_FACULTIES_FAILURE";

export const GET_DEPARTMENTS_REQUEST = "GET_DEPARTMENTS_REQUEST";
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const GET_DEPARTMENTS_FAILURE = "GET_DEPARTMENTS_FAILURE";